# Generated by Django 4.0.3 on 2022-09-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_transcription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcription',
            options={'verbose_name': 'Transcription', 'verbose_name_plural': 'Transcriptions'},
        ),
    ]
